servers:
  exam:
    username: user_exam
    password: password_exam
    uri: uri_exam
  test1:
    username: DIGITALL-IT-REG
    password: 05digitall-it19
    uri: https://epp.pubtest.nic.it/
  test2:
    username: DIGITALL-IT1-REG
    password: 05digitall-it19
    uri: https://epp.pubtest.nic.it/
  deleted1:
    username: DIGITALL-IT-REG
    password: 05digitall-it19
    uri: http://epp-deleted.pubtest.nic.it/
  deleted2:
    username: DIGITALL-IT1-REG
    password: 05digitall-it19
    uri: http://epp-deleted.pubtest.nic.it/
testpassword: pwtmp1234xx
mode: test
handleprefix: DGT-TST
samplecontacts:
  registrant1:
    name: Mario Rossi
  registrant2:
    name: Luigi Bianchi
  registrant3:
    name: John Doe
  techadmin1:
    name: Maria Callas
  techadmin2:
    name: Pico De Paperis
